version: "3.9"

x-common-keys: &common-keys
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

services:
  docs-nginx:
    <<: *common-keys
    container_name: pt-docs-nginx
    image: nginx:1.21-alpine
    ports:
      - "1186:80"
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/default.conf:rw
      - ${DOCS_IN_PATH}/_build:/var/www/:ro  # << DOCS IN is always latest
    deploy:
      resources:
        reservations:
          memory: 32m
        limits:
          memory: 64m
