#!/bin/bash
#------------------------------------------------------------------------------
# pytermor [ANSI formatted terminal output toolset]                           -
# (c) 2022-2023. A. Shavykin <0.delameter@gmail.com>                          -
# Licensed under GNU Lesser General Public License v3.0                       -
#------------------------------------------------------------------------------

main() {
    if [[ ! -f venv-demo/bin/python ]] ; then
        echo "Virtual environment is not present"
        echo -n "Initialize it in '$PWD/venv-demo'? "
        read -r -n1 -p'(y/n): ' yn
        case "$yn" in
            [Yy]*) init-venv || exit 1 ;;
                *) echo && exit 2 ;;
        esac
    fi

    local -a INTERPRETER=(python -q)
    if [[ $# -eq 0 ]] ; then
        echo "No args: checking if ipython is installed"
        if venv-demo/bin/pip show ipython &>/dev/null ; then
            INTERPRETER=(ipython)
        else
            echo "ipython not found, launching default interpreter"
        fi
    fi

    if [[ -f .run-startup.py ]] ; then
        PYTHONSTARTUP=.run-startup.py PYTHONPATH=. venv-demo/bin/${INTERPRETER[*]} "$@"
    else
        printf '%s\n' "import pytermor as pt" "print('imported pytermor %s as pt' % pt.__version__)" > /tmp/ptstartup
        PYTHONSTARTUP=/tmp/ptstartup PYTHONPATH=. venv-demo/bin/${INTERPRETER[*]} "$@"
        rm /tmp/ptstartup
    fi
}

init-venv() {
    echo
    if ! python -m venv venv-demo ; then
        echo "[CRITICAL] python 3.8 or higher is required, as well as installed 'virtualenv' package"
        return 1
    fi
    if ! venv-demo/bin/python -m pip install . ; then
        echo "[ERROR] failed to install source-distributed 'pytermor' into created venv. Ensure that working dir is same as the project root. Trying to install from package registry..."

        if ! venv-demo/bin/python -m pip install pytermor ; then
            echo "[CRITICAL] failed to install 'pytermor' even from the registry  # ToT"
            return 1
        fi
    fi
    venv-demo/bin/python -m pip install -r requirements-demo.txt || echo "[ERROR] Failed to install requirements"
}

main "$@"
