# -----------------------------------------------------------------------------
#  pytermor [ANSI formatted terminal output toolset]
#  (c) 2022. A. Shavykin <0.delameter@gmail.com>
# -----------------------------------------------------------------------------
# AUTOGENERATED MODULE
# ${created_at}
"""
Color preset list:
${counts}
"""
from .ansi import IntCode
from .color import Color16, Color256, ColorRGB


class ColorValuesXterm:
    """
    ColorValuesXterm
    """

    # fmt: off
${defs_xterm_16}

${defs_xterm_256}
    # fmt: on


class ColorValuesRGB:
    """
    ColorValuesRGB
    """

    # fmt: off
${defs_rgb}
    # fmt: on


cv = ColorValuesXterm
cvr = ColorValuesRGB
