# -----------------------------------------------------------------------------
#  pytermor [ANSI formatted terminal output toolset]
#  (c) 2022. A. Shavykin <0.delameter@gmail.com>
# -----------------------------------------------------------------------------
# AUTOGENERATED MODULE
# %t

from .color import Color16, Color256, ColorRGB
from .ansi import IntCode


# fmt: off
%s
# fmt: on
