# ---------------------------
# GM
# ---------------------------

- name: "Olympic Bronze"
  value: 0x4e3e37
- name: "Sunrise Coral"
  value: 0xc27863
- name: "Grecian Bronze"
  value: 0x923916
- name: "Brookmere Green"
  value: 0x3d504b
- name: "Aspen Green"
  value: 0x687652
- name: "Sequoia Beige"
  value: 0xb1b7af
- name: "Dawn Gray"
  value: 0x616359
- name: "Bamboo Cream"
  value: 0xf2e096
- name: "Victorian White"
  value: 0xf4e9ce
- name: "Ispahan Blue"
  value: 0x303940
- name: "Banff Blue"
  value: 0x83a9c1
